baseURL = "http://localhost"
languageCode = "en-us"
title = "Hands-On.Cloud"
theme = "hands-on-cloud"
pygmentsCodeFences = true
summaryLength = 40
enableRobotsTXT = true
timeout = 60000
disableLiveReload = true

[author]
    name = 'Andrei Maksimov'
    profile = 'Passionate Cloud Solutions Architect with 10+ years of experience.'
    avatar = 'https://avatars2.githubusercontent.com/u/1902417?s=460&v=4'

[Params]
    ampElements = ["amp-sidebar", "amp-carousel", "amp-bind", "amp-form", "amp-analytics", "amp-auto-ads", "amp-iframe", "amp-addthis"]
    logo = "hands-on-cloud-logo.png"
    header = "Hands-On.Cloud"
    localeOgp = "en-us"
    og_image = "/hands-on-cloud-logo.png"
    sitename = "Hands-On.Cloud"
    description = "This blog is where IT professionals all over the World find answers to their daily questions"
    keywords = "aws,python,docker,terraform,cloudformation,serverless,linux,kubernetes,bash"
    twitter = "andreivmaksimov"
    github = "andreivmaksimov"
    facebook = "andrei.maksimov.3"
    linkedin = "avmaksimov"
    instagram = "andrei_v_maksimov"
    googleanalytics = "UA-137355839-1"
    googlecustomsearch = "005409723859646106283:xrxw99mawa4"
    toc = true
    enableGitInfo = "true"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML", "AMP", "RSS"]
  section = ["HTML", "AMP", "RSS"]
  taxonomy = ["HTML", "AMP", "RSS"]
  term = ["HTML", "AMP", "RSS"]
